import {
  ReactComponentElement,
  ReactElement,
  ReactHTMLElement,
  ReactNode,
} from "react";
import { FirebaseProvider } from "@/libs/Firebase";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <FirebaseProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </FirebaseProvider>
  );
}
